IntelLabs/kAFL

kAFL-Fuzzer/fuzzer/process/master.py
Comma in the end makes debug_mode a tuple which is always True after casting to bool:
``` python
>>> debug_mode = False,
>>> bool(debug_mode)
True
```
=> master.py: fix debug_mode initialization

kAFL-Fuzzer/fuzzer/communicator.py
Default backlog value is 1 so if 2 slaves try to connect simultaneously, one of them will be denied by OS itself.
=> Do not refuse slave connections if they connect too fast

kAFL-Fuzzer/fuzzer/technique/havoc.py
The dictionary option was not working correctly because "string_escape" encoding does not exist in python3.
=> Fix dictionary digesting

kAFL-Fuzzer/common/qemu.py
`print_warning` expects one argument
=> fix logging of rq crash

install.sh
Now that we use set -e, we need to intercept possible non-null return codes
=> install.sh: fix return codes checking with set -e

Makefile, Pipfile
West 0.13 needs a minor fix in manifest path but this would break
existing installs. Pin 0.12 here and upgrade in a later release..
=> pin west to v0.12

README.md, manifest/west.yml
This PR updates the `workspace` branch before it becomes the new `master` in the future `v0.4` release.
- west: update `fuzzer` new location at [kafl.fuzzer](https://github.com/IntelLabs/kafl.fuzzer)
- README:
- copy README from `master` branch
- remove `git clone -b workspace`: simply clone `master`
=> Prepare release v0.4

deploy/Makefile
- use `grep's` return code instead of stdout to test whether inventory's file content is 'localhost ....'
- fix `ASK_BECOME_PASS` default value: when set to an empty string, Makefile's variable substitution would keep the strings
On a side note: Makefiles don't care about undefined variables used in a conditional statement ... (`GREP_FINDINGS`)
=> Fix makefile ask become pass

deploy/intellabs/kafl/roles/nyx_packer/defaults/main.yml, deploy/intellabs/kafl/roles/nyx_packer/tasks/main.yml
Moving the `nyx_packer` role from ccc repo to kafl.
It is not marked as a dependency of the `fuzzer` role, so it's an optional that will only be installed if explicitely requested, as
~~~yml
- role: intellabs.kafl.nyx_packer
~~~
=> add optional nyx_packer role

README.md, deploy/intellabs/kafl/roles/targets/defaults/main.yml
Not important enough to rename the repo, and its confusing to download
'targets' and then have an examples/ folder...
=> move targets repo back to targets folder

deploy/intellabs/kafl/roles/kernel/defaults/main.yml, deploy/intellabs/kafl/roles/kernel/tasks/install_kernel.yml, deploy/intellabs/kafl/roles/kernel/tasks/main.yml
The menuoption is a system-specific UUID and menutitle is
distro-specific, so this dynamically greps grub.cfg for the
first/best matching entry after kernel install..
Also modify conditional execute to allow "make deploy -- tags update_grub"
=> ansible: fix grub configuration to find correct menuentry

deploy/group_vars/all.yml, deploy/intellabs/kafl/roles/fuzzer/defaults/main.yml, deploy/site.yml
- expose remote installation target as workspace_root variable
- change default install to use ~/workspace/kafl/ with env.sh at toplevel
=> make remote installation configurable

.github/workflows/CI.yml, README.md, deploy/Makefile, deploy/host_vars/localhost.yml, deploy/inventory
Use Ansible's [host_vars](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#assigning-a-variable-to-one-machine-host-variables) to force `ansible_connection` to `local`.
Previous behavior was to force this in the `inventory`, but it had the be maintained in the makefile as well and not documented.
Now the inventory only contains `localhost`, which is more simple and explicit.
=> deploy: use host_vars to force local ansible_connection for localhost

deploy/requirements.txt
Bump Ansible from `5.7.1` to [`6.3.0`](https://groups.google.com/g/ansible-announce/c/PSbAe3qmQ0s) release
=> deploy: bump Ansible to 6.3.0

.github/workflows/CI.yml
Old docker image was broken due to custom APT repositories pointing to unmaintained servers.
New image: https://hub.docker.com/r/takeyamajp/debian-sshd
=> CI: update remote job's docker image

deploy/intellabs/kafl/roles/fuzzer/templates/env.j2
KAFL_CONFIG_FILE is now optional and can be used to override the package defaults at kafl_fuzzer/config_default.yaml.
For usability, keep the variable in env.sh and set it to this new package default.
=> KAFL_CONFIG_FILE: adopt new default path

deploy/intellabs/kafl/roles/fuzzer/meta/main.yml, deploy/intellabs/kafl/roles/fuzzer/tasks/main.yml
This PR improves #113 by removing the `include_role` hack, and using a conditional role dependency based on `install_nyx_packer` boolean variable value
=> fuzzer: set nyx_packer as optional dependency

deploy/intellabs/kafl/roles/fuzzer/defaults/main.yml, deploy/intellabs/kafl/roles/fuzzer/tasks/main.yml
This PR uses the official [`ansible.builtin.pip`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html) module to install the fuzzer, instead of custom commands.
Also it defines and exports a new variable: `fuzzer_venv_root`, which will be useful for he future `bkc` role @il-steffen
=> fuzzer: use official ansible pip module

deploy/intellabs/kafl/roles/qemu/tasks/main.yml
Switch from lto to static. LTO is quite slow and does not parallelize well:
$ time ./compile_qemu_nyx.sh lto     # real    3m43.203s
$ time ./compile_qemu_nyx.sh static # real    0m52.631s
This is easy for users to customize:
$ make env
$ cd $QEMU_ROOT
$ ./compile_qemu_nyx.sh debug
=> Switch to building qemu 'static' by default

.github/RELEASE.md, .github/RELEASE.txt, .github/workflows/CI.yml
Follow kafl_fuzzer's [RELEASE.md](https://github.com/IntelLabs/kafl.fuzzer/commit/6cf99e51294ff5c8db773a7673a2870929262116?short_path=4faaf54#diff-4faaf5456b1682f37cdfd0acf72d3e030f0c757a6e1d429614920d6a16fa300f) style
=> .github: adopt new RELEASE changelog style

.github/workflows/docs.yml
This is required so that `git describe --abbrev=0` can fetch the latest tag:
=> ci: fetch whole history in docs workflow

.github/workflows/docs.yml, docs/source/conf.py
Following:
https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
=> Fix docs GitHub pages

deploy/intellabs/kafl/roles/fuzzer/tasks/main.yml
Following https://github.com/IntelLabs/kafl.fuzzer/pull/43
=> fuzzer: remove libgraphviz-dev dependency

Makefile, README.md
Current main page is rather unhelpful with getting started.
After fancy expose of features, the user is lead to a different page which (in my case) has some text but no obvious links to next step. Once I find the "next" button at the far bottom of the page, I get a bit overwhelming full page installation guide with lots of colorful boxes. Its quite difficult to fish out requirements and 2-3 relevant commands between all the boxes and highlights. 
- this patch adds requirements + getting started section back in
- suggest to revise the installation guide for better overview + in depth background on possible problems, like checking for HW support
- tutorials should start with 'make env' (too much for this 'getting started' section)
=> better getting started

deploy/intellabs/kafl/roles/qemu/defaults/main.yml, deploy/intellabs/kafl/roles/qemu/tasks/main.yml
Following https://github.com/IntelLabs/kafl.qemu/pull/3
This will help to create a clean Docker image with only static binaries
=> qemu: add qemu_build_type default option

.github/RELEASE.md, docs/source/index.md, docs/source/reference/fuzzer_configuration.md
Following https://github.com/IntelLabs/kafl.fuzzer/pull/52
=> docs: move fuzzer_configuration from kafl.fuzzer

.dockerignore, .github/DOCKER.md, .github/RELEASE.md, .github/workflows/CI.yml, .github/workflows/security.yml, Dockerfile, deploy/intellabs/kafl/roles/fuzzer/tasks/main.yml, deploy/intellabs/kafl/roles/kernel/tasks/main.yml, docs/source/tutorials/fuzzing_linux_kernel.md
Reopen this PR from #104 
This PR Dockerize the kAFL fuzzer.
It's based on https://github.com/Wenzel/kAFL/tree/docker_workspace, updated with the new Ansible deployment.
To build the image:
```shell
docker build -t kafl .
```
To apply that image on [fuzzing the linux kernel tutorial](https://intellabs.github.io/kAFL/tutorials/fuzzing_linux_kernel.html)
*Make sure to create the workdir beforehand*, otherwise the Docker daemon will create it as `root:root` and `kafl` will fail.
```shell
docker run \
-ti --rm \
--device /dev/kvm \
-v $(pwd)/kafl_config.yaml:/mnt/kafl_config.yaml \
-v /dev/shm/kafl:/mnt/workdir \
-v $(pwd)/linux-guest/arch/x86/boot/bzImage:/mnt/kernel \
-e KAFL_CONFIG_FILE=/mnt/kafl_config.yaml \
--user $(id -u):$(id -g) \
--group-add $(getent group kvm | cut -d: -f3) \
kafl …
```
=> Dockerize kAFL

.github/RELEASE.md, Dockerfile
Linux kernel example uses a `virtio-net` device, which requires `pc-bios/efi-virtio.rom` file not included in the final Docker image.
This PR fixes that.
=> docker: include QEMU pc-bios/*.rom files

.github/RELEASE.md, .github/workflows/CI.yml
push `intellabs/kafl:latest` tag by default
=> ci: push use latest tag for intellabs/kafl image

.github/workflows/CI.yml, .github/workflows/docs.yml, .github/workflows/security.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> ci: deprecate nodejsv12 based actions

.github/RELEASE.md, .github/workflows/CI.yml
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
=> ci: deprecate ubuntu-18.04 runner

.github/RELEASE.md, .github/workflows/CI.yml, README.md, deploy/intellabs/kafl/roles/examples/tasks/main.yml, deploy/intellabs/kafl/roles/examples/tasks/template_windows.yml, docs/source/reference/deployment.md
Updates the playbook with a new section under `examples` role, conditioned by `examples-template-windows` tag being specified.
installs the following packages:
- vagrant 2.3.6-1
- packer
- gcc-mingw-w64-x86-64
- libvirt-dev
- ruby-dev
and setup the qemu-bridge-helper as setuid, which is required to allow vagrant to setup the network in `qemu:///session` mode
Related: https://github.com/IntelLabs/kafl.targets/pull/21
=> Conditionally install required tooling to build Windows VM template in order to run Windows examples

.github/RELEASE.md, deploy/intellabs/kafl/roles/qemu/defaults/main.yml
Following recent QEMU [`v0.7`](https://github.com/IntelLabs/kafl.qemu/releases/tag/v0.7) release, pin the tag instead of tracking a branch.
=> qemu: pin qemu_revision to a specific tag, not branch

.github/RELEASE.md, docs/source/tutorials/fuzzing_linux_kernel.md
- related https://github.com/IntelLabs/kafl.fuzzer/pull/68
- also remove explicit `KAFL_CONFIG_FILE` and rely on the default configuration to load `kafl.yaml` from current working directory (depends on https://github.com/IntelLabs/kafl.targets/pull/23)
=> Docs: Update Linux kernel tutorial to use implicit IP parameters from state.yaml snapshot file

docs/source/reference/hypercall_api.md
reported by @Gehim12
related #229 
Implementation in QEMU:
https://github.com/IntelLabs/kafl.qemu/blob/kafl_stable/nyx/hypercall/hypercall.c#L296
```c
if (buffer[0] != 0 && buffer[1] != 0) {
GET_GLOBAL_STATE()->pt_ip_filter_a[buffer[2]]          = buffer[0];
GET_GLOBAL_STATE()->pt_ip_filter_b[buffer[2]]          = buffer[1];
GET_GLOBAL_STATE()->pt_ip_filter_configured[buffer[2]] = true;
nyx_debug_p(CORE_PREFIX, "Configured range register IP%ld: 0x%08lx-0x%08lx\n",
buffer[2], buffer[0], buffer[1]);
```
=> docs: fix range_submit hypercall buffer indexes

Dockerfile
Fix #248 
```python
[7] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
File "pathlib.py", line 14, in <module>
File "urllib/parse.py", line 40, in <module>
ModuleNotFoundError: No module named 'ipaddress'
Traceback (most recent call last):
File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[7] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```
=> docker: upgrade pyinstaller to v6.1.0

deploy/intellabs/kafl/roles/examples/defaults/main.yml, deploy/intellabs/kafl/roles/examples/tasks/dvkm.yml, deploy/intellabs/kafl/roles/examples/tasks/main.yml, docs/source/reference/deployment.md
This PR goes with another kafl.targets PR that adds a new example based on the Damn Vulnerable Kernel Module
=> add dvkm example

.github/RELEASE.md, deploy/intellabs/kafl/roles/libxdc/defaults/main.yml, deploy/intellabs/kafl/roles/qemu/defaults/main.yml
Fixes https://github.com/IntelLabs/kafl.linux/issues/10
Upgrade:
- `kafl.qemu` to [`v0.8`](https://github.com/IntelLabs/kafl.qemu/releases/tag/v0.8)
- `kafl.libxdc` to [`v0.2`](https://github.com/IntelLabs/kafl.libxdc/releases/tag/v0.2) (pinned)
=> deploy: update QEMU and libxdc to fix 6.0 regression

.github/RELEASE.md, docs/source/reference/hypercall_api.md
Reported by @sangjun
Fixed #251
=> docs: fix hypercall argument for DUMP_FILE

deploy/intellabs/kafl/roles/examples/tasks/template_windows.yml, docs/source/tutorials/windows/windows_template.md
Following https://github.com/IntelLabs/kafl.targets/pull/36
We don't need to pin Vagrant to 2.3.6 anymore
=> deploy: remove Vagrant pinning

deploy/intellabs/kafl/roles/kernel/defaults/main.yml
This PR adds support for Nyx kernel based on 6.8.0 Linux kernel.
=> deploy: add nyx kernel 6.8

docs/source/tutorials/installation.md
Fix #288 
Requires https://github.com/IntelLabs/kafl.fuzzer/releases/tag/v0.6.1
=> tutorial: clarify when kafl fuzz succeeds

deploy/intellabs/kafl/roles/examples/tasks/template_windows.yml
Hi,
This PR addresses the dependency on Libvirt required by Vagrant. The `libvirt-daemon-system` package installs the `libvirtd.service` along with other necessary sockets (e.g., network). I hope this is helpful.
Looking forward to your feedback and wishing you a productive day!
=> example: fix libvirt tooling dependency
