.github/workflows/CI.yml

https://github.com/actions/cache/issues/820

ci: remove cache following github action failure

---

deploy/intellabs/kafl/roles/capstone/tasks/main.yml
deploy/intellabs/kafl/roles/fuzzer/tasks/main.yml
deploy/intellabs/kafl/roles/libxdc/tasks/main.yml
deploy/intellabs/kafl/roles/qemu/tasks/main.yml
deploy/intellabs/kafl/roles/radamsa/tasks/main.yml
deploy/intellabs/kafl/roles/targets/tasks/main.yml

Add the `clone` tag to only clone the repos.
`make deploy -- --tags clone`

add clone tag

---

.gitignore
Makefile
deploy/intellabs/kafl/roles/fuzzer/tasks/post_tasks.yml
deploy/intellabs/kafl/roles/fuzzer/templates/env.j2
deploy/site.yml
deploy/templates/env.j2

same as ccc repo, but did some more updates to env.j2 to be more consistent with old behavior + ccc layout

Explicit env file

---

Makefile
deploy/Makefile
deploy/intellabs/kafl/roles/capstone/meta/defaults.yml
deploy/intellabs/kafl/roles/capstone/tasks/main.yml
deploy/intellabs/kafl/roles/default_vars_only/defaults/main.yml
deploy/intellabs/kafl/roles/fuzzer/tasks/main.yml
deploy/intellabs/kafl/roles/kernel/meta/main.yml
deploy/intellabs/kafl/roles/libxdc/meta/main.yml
deploy/intellabs/kafl/roles/libxdc/tasks/main.yml
deploy/intellabs/kafl/roles/nyx_packer/meta/main.yml
deploy/intellabs/kafl/roles/nyx_packer/tasks/main.yml
deploy/intellabs/kafl/roles/qemu/meta/main.yml
deploy/intellabs/kafl/roles/qemu/tasks/main.yml
deploy/intellabs/kafl/roles/radamsa/meta/main.yml
deploy/intellabs/kafl/roles/radamsa/tasks/main.yml
deploy/intellabs/kafl/roles/targets/meta/main.yml
deploy/intellabs/kafl/roles/targets/tasks/main.yml

Solve https://github.com/IntelLabs/kAFL/issues/79

Developer targets

---

deploy/intellabs/kafl/roles/qemu/tasks/main.yml

disable recursive qemu pull

---

deploy/site.yml

Linux targets use lowercase http_proxy/https_proxy

fix adopting default proxy settings from environment

---

.github/workflows/CI.yml

Test deployment compatibility with Ubuntu 22.04

CI: add support for ubuntu-22.04

---

deploy/Makefile

deploy/Makefile: make venv depend on ansible-galaxy binary's presence

---

deploy/intellabs/kafl/roles/fuzzer/tasks/main.yml
deploy/intellabs/kafl/roles/kernel/tasks/main.yml
deploy/intellabs/kafl/roles/kernel/tasks/pre_tasks.yml

kernel: perform hardware check as pre_tasks

---

deploy/intellabs/kafl/roles/fuzzer/meta/main.yml
deploy/intellabs/kafl/roles/ghidra/defaults/main.yml
deploy/intellabs/kafl/roles/ghidra/meta/main.yml
deploy/intellabs/kafl/roles/ghidra/tasks/main.yml
deploy/templates/env.j2

Installs [Ghidra](https://ghidra-sre.org/) in `kafl` root folder
Helps to fix #75

Add Ghidra role

---

.github/workflows/CI.yml

Add tests based on https://github.com/nyx-fuzz/Nyx-Testing

ci: add Nyx-Testing tests

---

deploy/intellabs/kafl/roles/fuzzer/templates/env.j2

Following https://github.com/IntelLabs/kafl.fuzzer/pull/22

deploy: disable KAFL_CONFIG_FILE

---

README.md

- disclaimer up front
- reduce italics/emphasis

README polishing

---

.github/RELEASE.md
docs/source/tutorials/fuzzing_linux_kernel.md

Update tutorial according to https://github.com/IntelLabs/kafl.fuzzer/pull/22

docs: update tutorial with latest kafl command line

---

docs/source/reference/workdir_layout.md

Follow https://github.com/IntelLabs/kafl.fuzzer/pull/22
- `config (msgpack)` -> `config.yaml (YAML)`
- `kafl_xxx.py` -> `kafl xxx`

docs/source/reference/workdir_layout: fix layout

---

.github/workflows/CI.yml
.github/workflows/security.yml

fix https://github.com/IntelLabs/kAFL/actions/runs/4136409350/jobs/7150230971

CI: fix build_image and Snyk jobs

---

.github/RELEASE.md
deploy/intellabs/kafl/roles/kernel/tasks/pre_tasks.yml

kernel: fix checking pmu_name for AlderLake

---

.github/RELEASE.md
docs/source/reference/fuzzer_configuration.md

fix https://github.com/IntelLabs/kAFL/issues/171 
Also related https://github.com/IntelLabs/kafl.fuzzer/pull/62

docs: document grimoire fuzzer config key

---

.github/RELEASE.md
deploy/intellabs/kafl/roles/kernel/defaults/main.yml
deploy/intellabs/kafl/roles/kernel/files/support_test.c

Kernel/nyx 6.0

---

.github/workflows/CI.yml

not compatible with kafl kernel 6.0

ci: remove nyx-testing

---

.github/RELEASE.md
deploy/intellabs/kafl/roles/examples/tasks/template_windows.yml

examples: use bash to unpack GPG

---

deploy/intellabs/kafl/roles/examples/defaults/main.yml

Pin latest kafl.targets release

examples: pin v0.3
